### ISSUE TITLE
Only works on Windows

### ISSUE THREAD

**Issue by Exscotticus** [AliFlux/MapTilesDownloader#2]
Looks like you have some Windows OS specific code...

```
$ python3 server.py
Starting Server...
Running Server...
Traceback (most recent call last):
  File "server.py", line 167, in <module>
    run()
  File "server.py", line 162, in run
    os.startfile('UI\\index.htm', 'open')
AttributeError: module 'os' has no attribute 'startfile'
```

**Comment by AliFlux** [comment]
You're right. Just checked the documentation, the startfile is Windows specific. For now, you can comment out the line and manually open the `UI\index.htm` in your browser. I've found a fix for this that I'll apply soon.

**Comment by Exscotticus** [comment]
Yeah it was by no means a show stopper. I just replaced the line with something that would work for me on my Mac...

`os.system('open -a "Google Chrome" UI/index.htm')`

Fantastic app, btw. So much fun to watch the threads working.

Any way to change the main preview map from the UI? It would be nice if, after you select a different map, the preview map would switch to that as well.

**Comment by AliFlux** [comment]
Thanks, that's a great idea. I'll keep this in mind for the next iteration.

**Comment by AliFlux** [comment]
The newest commit is decoupled from OS desktop (for compatibility with docker). It won't automatically open the browser anymore

**Comment by RussellTaylor83** [comment]
@AliFlux Fantastic repo. Just catching up with it, can this issue be closed?
