### ISSUE TITLE
Map Tiles Downloader no longer loading map screen

### ISSUE THREAD

**Issue by crawl55** [AliFlux/MapTilesDownloader#32]
When loading the app, the map screen allowing you to select a geographical area no longer works.  The following is displayed in the CMD prompt.  

127.0.0.1 - - [30/Jan/2023 19:14:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /materialize/css/materialize.min.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /fonts/fonts.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /style.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /jquery.min.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /mapbox-gl-draw-rectangle-mode.min.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /async.min.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:04] "GET /turf.min.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:05] "GET /materialize/js/materialize.min.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:05] "GET /main.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:05] "GET /fonts/open-sans-v15-latin-700.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:05] "GET /fonts/open-sans-v15-latin-600.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:05] "GET /fonts/open-sans-v15-latin-regular.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2023 19:14:05] "GET /favicon.ico HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50470)
Traceback (most recent call last):
  File "C:\Users\alanr\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\alanr\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\alanr\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Users\alanr\AppData\Local\Programs\Python\Python311\Lib\http\server.py", line 432, in handle
    self.handle_one_request()
  File "C:\Users\alanr\AppData\Local\Programs\Python\Python311\Lib\http\server.py", line 420, in handle_one_request
    method()
  File "C:\Users\alanr\Desktop\MapTilesDownloade\src\server.py", line 219, in do_GET
    with open(file, "rb") as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './UI/favicon.ico'

**Comment by sgooding** [comment]
I, also, get the same error in the docker version.

**Comment by islandtriumph96** [comment]
I cant load the map either anymore. bummer this was probably my favorite script on here. I am wondering about the favicon bit actually I remember researching about converting to geotiff from mbtfiles and remember seeing favicon as a company

**Comment by islandtriumph96** [comment]
all I can think of is that mapbox changed its API recently and its not able to find the favicon. because in the UI folder locally there's no favicon.ico

**Comment by islandtriumph96** [comment]
disregard I found out that he rotated his access token. I made an account and put in my token in main.js and now it loads just fine

**Comment by khatkhuong** [comment]
@islandtriumph96 Can you explain in details?

**Comment by avanmalleghem** [comment]
@khatkhuong
1) Create an account on mapbox : https://www.mapbox.com/mapbox-gljs . You will get a default key.
2) Replace the key in "main.js" file by your key.

**Comment by elliottetzkorn** [comment]
I am having the same issue. I can get the server up and running, but nothing shows on the browser.

**Comment by xumaxie** [comment]
我解决了该问题，我在windows环境下使用Docker来下载影像。
1. 首先，在MapTilesDownloader-master\src\UI\main.js中设置自己的mapbox的key,
2. 使用作者给的Dockerfile自建docker image（因为如果执行作者给的Docker，则使用的是作者的image我们本地修改的key并不能生效）因此需要执行docker build -t 镜像名字xx .
3. 之后执行作者给的docker命令，我们在windows下需要修改为docker run -v "%cd%"/output:/app/output/ -p 8080:8080 -it 镜像名字xx  即可。

**Comment by muddatrukka** [comment]
MapBox requires a credit card even for free use.

**Comment by Waffle1434** [comment]
rip

**Comment by fanthos** [comment]
SImply replace mapbox with maplibre and style file fixes the issue.

**Comment by myfta** [comment]
> SImply replace mapbox with maplibre and style file fixes the issue.

Please could you explain how main.js needs to be modified to replace mapbox with maplibre.

What are the style file fixes?

How does this fix the token issue? Is one not used with maplibre?

Thanks.

**Comment by AliFlux** [comment]
Hello people. Thanks to the much needed PR #45 , the downloader works again! 🚀
P.S. There's a brand new Electron+Svelete downloader I started working on few years ago. It also needs a Mapbox -> Maplibre replacement. Stay tuned
