### ISSUE TITLE
error while relaying tile/ KeyError: 'CONTENT-LENGTH'

### ISSUE THREAD

**Issue by bribrah** [AliFlux/MapTilesDownloader#4]
Whenever the tool tries to download the tiles I'm getting error "error while relaying tile". In the python console the error output looks like so: 
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59134)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\ProgramData\Anaconda3\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\ProgramData\Anaconda3\lib\http\server.py", line 414, in handle_one_request
    method()
  File "server.py", line 81, in do_POST
    postvars = parse_multipart(self.rfile, pdict)
  File "C:\ProgramData\Anaconda3\lib\cgi.py", line 220, in parse_multipart
    headers['Content-Length'] = pdict['CONTENT-LENGTH']
KeyError: 'CONTENT-LENGTH'
----------------------------------------
```

**Comment by bribrah** [comment]
when runnin with non anaconda python I get the following error: in the javascript console: `jquery.min.js:2 POST http://127.0.0.1:11291/download-tile net::ERR_EMPTY_RESPONSE`
Don't get any errors in python console

**Comment by AliFlux** [comment]
Hi. Which python version are you using?

**Comment by bribrah** [comment]
I have tried with both 3.7.4 and 3.5.0

**Comment by bribrah** [comment]
I am no longer getting error weirdly. Thanks for concern though!
