### ISSUE TITLE
Error while relaying tile - what to do?

### ISSUE THREAD

**Issue by GOblin3k555** [AliFlux/MapTilesDownloader#6]
Hi!
I tried to use your script for downloading map tiles. I got an error after selecting a region and trying to download the tiles.
"9652,12319,15 : Error while relaying tile
All requests are done"

In terminal it looks like this:
----------------------------------------
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
Exception happened during processing of request from ('127.0.0.1', 61176)
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 414, in handle_one_request
    method()
Traceback (most recent call last):
  File "C:\Users\KK\Desktop\Nowy folder (3)\server.py", line 81, in do_POST
    postvars = parse_multipart(self.rfile, pdict)
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\KK\Desktop\Nowy folder (3)\server.py", line 81, in do_POST
    postvars = parse_multipart(self.rfile, pdict)
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\cgi.py", line 220, in parse_multipart
    headers['Content-Length'] = pdict['CONTENT-LENGTH']
KeyError: 'CONTENT-LENGTH'
  File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\cgi.py", line 220, in parse_multipart
    headers['Content-Length'] = pdict['CONTENT-LENGTH']
----------------------------------------
KeyError: 'CONTENT-LENGTH'

Any idea of what the issue is here? I have no experience in coding etc. Would be great to hear back from you!
Krzysztof

**Comment by AliFlux** [comment]
Hi, you're probably using older versions of python. The recent commit provides support for more versions, you can test it out and see if the issue still persists.
